//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 02:43:31 PM COT 
//


package com.banistmo.rest.client.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.banistmo.security.clients.rest.admonchannels.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ChannelRS_QNAME = new QName("http://banistmo.com/message/security/services/adminChannels", "channelRS");
    private final static QName _ChannelRQ_QNAME = new QName("http://banistmo.com/message/security/services/adminChannels", "channelRQ");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.banistmo.security.clients.rest.admonchannels.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ChannelRQType }
     * 
     */
    public ChannelRQType createChannelRQType() {
        return new ChannelRQType();
    }

    /**
     * Create an instance of {@link ChannelSecurityProfileRSType }
     * 
     */
    public ChannelSecurityProfileRSType createChannelSecurityProfileRSType() {
        return new ChannelSecurityProfileRSType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link AvailableTimesType }
     * 
     */
    public AvailableTimesType createAvailableTimesType() {
        return new AvailableTimesType();
    }

    /**
     * Create an instance of {@link OperationalDayType }
     * 
     */
    public OperationalDayType createOperationalDayType() {
        return new OperationalDayType();
    }

    /**
     * Create an instance of {@link ChannelSecurityProfileType }
     * 
     */
    public ChannelSecurityProfileType createChannelSecurityProfileType() {
        return new ChannelSecurityProfileType();
    }

    /**
     * Create an instance of {@link ValidationType }
     * 
     */
    public ValidationType createValidationType() {
        return new ValidationType();
    }

    /**
     * Create an instance of {@link SpecialDatesType }
     * 
     */
    public SpecialDatesType createSpecialDatesType() {
        return new SpecialDatesType();
    }

    /**
     * Create an instance of {@link SchedulesType }
     * 
     */
    public SchedulesType createSchedulesType() {
        return new SchedulesType();
    }

    /**
     * Create an instance of {@link GrantTypes }
     * 
     */
    public GrantTypes createGrantTypes() {
        return new GrantTypes();
    }

    /**
     * Create an instance of {@link AllowedResourcesType }
     * 
     */
    public AllowedResourcesType createAllowedResourcesType() {
        return new AllowedResourcesType();
    }

    /**
     * Create an instance of {@link AllowedTransactionType }
     * 
     */
    public AllowedTransactionType createAllowedTransactionType() {
        return new AllowedTransactionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelSecurityProfileRSType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://banistmo.com/message/security/services/adminChannels", name = "channelRS")
    public JAXBElement<ChannelSecurityProfileRSType> createChannelRS(ChannelSecurityProfileRSType value) {
        return new JAXBElement<ChannelSecurityProfileRSType>(_ChannelRS_QNAME, ChannelSecurityProfileRSType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelRQType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://banistmo.com/message/security/services/adminChannels", name = "channelRQ")
    public JAXBElement<ChannelRQType> createChannelRQ(ChannelRQType value) {
        return new JAXBElement<ChannelRQType>(_ChannelRQ_QNAME, ChannelRQType.class, null, value);
    }

}
