//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 02:43:31 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://banistmo.com/message/security/services/adminChannels", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.banistmo.rest.client.message;
